export { default as AccordionElement } from './AccordionElement'
export { default as BgSlider } from './BgSlider'
export { default as ClientSlider } from './ClientSlider'
export { default as DarkSlider } from './DarkSlider'
export { default as Future } from './Future'
export { default as GetInTouch } from './GetInTouch'
export { default as Hero } from './Hero'
export { default as HeroBottom } from './HeroBottom'
export { default as HomeServices } from './HomeServices'
export { default as SimpleContent } from './SimpleContent'
export { default as SlideSection } from './SlideSection'
export { default as TrustedPartner } from './TrustedPartner'
export { default as Vision } from './Vision'

